spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kubsuAppDB
    username: postgres
    password: 5555
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

kubsuAppAPI:
  app:
    jwtSecret: flkajsfdwehjrtnvmsp
    jwtExpirationMs: 18000000